export const menus = {
  superuser: [
    { name: 'Main/overview', href: 'superuser/main/overview' },
    { name: 'Administration/audit-logs', href: 'superuser/administration/audit-logs' },
    { name: 'Administration/system-settings', href: 'superuser/administration/system-settings' },
    { name: 'Administration/user-roles-permissions', href: 'superuser/administration/user-roles-permissions' },
    { name: 'Finance/billing-invoices', href: 'superuser/finance/billing-invoices' },
    { name: 'Finance/expenses', href: 'superuser/finance/expenses' },
    { name: 'Finance/financial-reports', href: 'superuser/finance/financial-reports' },
    { name: 'Finance/insurance-claims', href: 'superuser/finance/insurance-claims' },
    { name: 'Human-Resources/attendance-shifts', href: 'superuser/human-resources/attendance-shifts' },
    { name: 'Human-Resources/doctor-staff-management', href: 'superuser/human-resources/doctor-staff-management' },
    { name: 'Human-Resources/payroll', href: 'superuser/human-resources/payroll' },
    { name: 'Operations/appointments-management', href: 'superuser/operations/appointments-management' },
    { name: 'Operations/patient-management', href: 'superuser/operations/patient-management' },
    { name: 'Operations/pharmacy-inventory', href: 'superuser/operations/pharmacy-inventory' },
    { name: 'Reports-Analytics/overview', href: 'superuser/reports-analytics/overview' },
    { name: 'Reports-Analytics/patient-reports', href: 'superuser/reports-analytics/patient-reports' },
    { name: 'Reports-Analytics/financial-reports', href: 'superuser/reports-analytics/financial-reports' },
  ],
  doctor: [
    { name: 'Overview/patient-records', href: 'doctor/overview/patient-records' },
    { name: 'Overview/prescriptions', href: 'doctor/overview/prescriptions' },
    { name: 'Patients/appointments', href: 'doctor/patients/appointments' },
    { name: 'Patients/medical-history', href: 'doctor/patients/medical-history' },
    { name: 'Pharmacy/medication-inventory', href: 'doctor/pharmacy/medication-inventory' },
    { name: 'Pharmacy/prescription-management', href: 'doctor/pharmacy/prescription-management' },
    { name: 'Reports/patient-reports', href: 'doctor/reports/patient-reports' },
  ],
  staff: [
    { name: 'Appointments/schedule', href: 'staff/appointments/schedule' },
    { name: 'Patients/registration', href: 'staff/patients/registration' },
    { name: 'Point-of-Sale/billing', href: 'staff/point-of-sale/billing' },
    { name: 'Point-of-Sale/payments', href: 'staff/point-of-sale/payments' },
    { name: 'Inventory/stock-management', href: 'staff/inventory/stock-management' },
    { name: 'Inventory/suppliers', href: 'staff/inventory/suppliers' },  
  ],
}
